### ISSUE TITLE
Support for python 3.7

### ISSUE THREAD

**Issue by kolorafa** [blaa/WaveSync#1]
$ wavesync 
  File "/usr/bin/wavesync", line 1006
    asyncio.async(play)
                ^
SyntaxError: invalid syntax

Python 3.7.2
https://stackoverflow.com/a/53158394/1675736

Way to donate that great project would be nice too :)

**Comment by kolorafa** [comment]
Replacing asyncio.async with asyncio.ensure_future does the trick, but don't know if it's the correct way.

**Comment by blaa** [comment]
Wow, thanks. I'll look into it. I though I'm the only one using it. 

I had some improvements in mind but it "worked for me", so I didn't touch it for some time. :)


On 27 January 2019 15:38:55 CET, kolorafa <notifications@github.com> wrote:
>Replacing asyncio.async with asyncio.ensure_future does the trick, but
>don't know if it's the correct way.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blaa/WaveSync/issues/1#issuecomment-457923238

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blaa** [comment]
async() was deprecated alias since python 3.4. There is also once better name, but not backward compatible, so let's leave it like this. I released change on PyPI as 1.1.1 - it runs on my machines, you can test it. ;)
