### ISSUE TITLE
Public announcement system

### ISSUE THREAD

**Issue by shreshthtuli** [blaa/WaveSync#10]
Hi! I am trying to build a public announcement system using wavesync.

I wanted to record audio from a mic at one node in a network using sox recorder and direct it to the socket /tmp/music.source, so that it can be played in other nodes in sync. However, I am unable to understand in what format to send to the socket. Please help.

**Comment by blaa** [comment]
It would be probably easiest to use pulseaudio as an intermediate - that way you can use pretty  much any software to record the mic.
But the unix pipe approach is fine as well: it's just samples; So if you configure stereo, 16 bit samples at 44100 - that's what is expected:
2-byte (16bit) sample for one channel, 2-byte sample for another channel - at 44100 frames (sample pairs) per second.

In general - little endian encoded, which might get tricky if you have some big endian devices involved. Doubtfully though - but it happened actually. ;)

Tell me how it goes, good luck there. I've opened branch with some fixes and different approach, but haven't yet had time to finish this changes and test them.  The master branch should be cool though.

**Comment by shreshthtuli** [comment]
Thanks. I finally used snapserver for the same. 
Thanks for the help though.
