### ISSUE TITLE
Possible to use this for 7.1 channels?

### ISSUE THREAD

**Issue by klattimer** [blaa/WaveSync#6]
Is it at all possible to get this working for a multi-channel audio output?

**Comment by blaa** [comment]
Currently probably not, but it should be trivial to alter to work with 7.1. I've got no audio like that to test, but can blind-try to fix it if you're willing to put it to test.

As long as 7.1 works in pulseaudio/pyaudio as stuffing 7(8?) samples next to each other in a frame - nothing stops this idea from working.

**Comment by blaa** [comment]
I've dropped the artificial limit on number of channels in 2.1.0 - you can test it in 7.1 configuration I guess. I'm not able to test it currently so I can only guess. ;) Wavesync doesn't do much with the audio it synchronizes so it might just work.
